// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type MaintenanceGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/home/controllers/home_controller.ts').default['maintenance'], false>
}
type MentionsLegalesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/home/controllers/home_controller.ts').default['mentionsLegales'], false>
}
type CguGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/home/controllers/home_controller.ts').default['cgu'], false>
}
type PolitiqueConfidentialiteGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/home/controllers/home_controller.ts').default['privacy'], false>
}
type LoginGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/sign_in_controller.ts').default['show'], false>
}
type LoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/auth/validators.ts')['signInValidator']>>
  response: MakeTuyauResponse<import('../app/auth/controllers/sign_in_controller.ts').default['handle'], true>
}
type LogoutGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/sign_out_controller.ts').default['handle'], false>
}
type SignUpGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/sign_up_controller.ts').default['show'], false>
}
type SignUpPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/auth/validators.ts')['signUpValidator']>>
  response: MakeTuyauResponse<import('../app/auth/controllers/sign_up_controller.ts').default['handle'], true>
}
type ForgotPasswordGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/forgot_password_controller.ts').default['show'], false>
}
type ForgotPasswordPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/auth/validators.ts')['forgotPasswordValidator']>>
  response: MakeTuyauResponse<import('../app/auth/controllers/forgot_password_controller.ts').default['handle'], true>
}
type ResetpasswordIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/reset_password_controller.ts').default['show'], false>
}
type ResetpasswordIdPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/auth/validators.ts')['resetPasswordValidator']>>
  response: MakeTuyauResponse<import('../app/auth/controllers/reset_password_controller.ts').default['handle'], true>
}
type DashboardPublicitiesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/publicity/controllers/publicity_controller.ts').default['index'], false>
}
type DashboardPublicitiesCreateGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/publicity/controllers/publicity_controller.ts').default['create'], false>
}
type DashboardPublicitiesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/publicity/validators.ts')['createPublicityValidator']>>
  response: MakeTuyauResponse<import('../app/publicity/controllers/publicity_controller.ts').default['store'], true>
}
type DashboardPublicitiesIdEditGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/publicity/controllers/publicity_controller.ts').default['edit'], false>
}
type DashboardPublicitiesIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/publicity/validators.ts')['updatePublicityValidator']>>
  response: MakeTuyauResponse<import('../app/publicity/controllers/publicity_controller.ts').default['update'], true>
}
type DashboardPublicitiesIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/publicity/controllers/publicity_controller.ts').default['destroy'], false>
}
type DashboardPublicitiesIdStatsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/publicity/controllers/publicity_controller.ts').default['stats'], false>
}
type DashboardPublicitiesAdminGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/publicity/validators.ts')['listPublicityValidator']>>
  response: MakeTuyauResponse<import('../app/publicity/controllers/publicity_admin_controller.ts').default['index'], true>
}
type DashboardPublicitiesAdminIdApprovePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/publicity/controllers/publicity_admin_controller.ts').default['approve'], false>
}
type DashboardPublicitiesAdminIdRejectPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/publicity/controllers/publicity_admin_controller.ts').default['reject'], false>
}
type DashboardPubIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/publicity/controllers/publicity_controller.ts').default['show'], false>
}
type ApiEvtCollectPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/publicity/validators.ts')['trackPublicityValidator']>>
  response: MakeTuyauResponse<import('../app/publicity/controllers/publicity_tracking_controller.ts').default['track'], true>
}
type ApiMobileV1AuthLoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/mobile/validators.ts')['mobileLoginValidator']>>
  response: MakeTuyauResponse<import('../app/mobile/controllers/auth_controller.ts').default['login'], true>
}
type ApiMobileV1AuthRegisterPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/mobile/validators.ts')['mobileRegisterValidator']>>
  response: MakeTuyauResponse<import('../app/mobile/controllers/auth_controller.ts').default['register'], true>
}
type ApiMobileV1AuthForgotpasswordPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/mobile/validators.ts')['mobileForgotPasswordValidator']>>
  response: MakeTuyauResponse<import('../app/mobile/controllers/auth_controller.ts').default['forgotPassword'], true>
}
type ApiMobileV1AuthMeGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/auth_controller.ts').default['me'], false>
}
type ApiMobileV1AuthLogoutDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/auth_controller.ts').default['logout'], false>
}
type ApiMobileV1PushRegisterPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/mobile/validators.ts')['mobileRegisterPushTokenValidator']>>
  response: MakeTuyauResponse<import('../app/mobile/controllers/push_controller.ts').default['register'], true>
}
type ApiMobileV1PushUnregisterDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/push_controller.ts').default['unregister'], false>
}
type ApiMobileV1PostsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/posts_controller.ts').default['index'], false>
}
type ApiMobileV1PostsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/mobile/validators.ts')['mobileCreatePostValidator']>>
  response: MakeTuyauResponse<import('../app/mobile/controllers/posts_controller.ts').default['store'], true>
}
type ApiMobileV1PostsIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/posts_controller.ts').default['show'], false>
}
type ApiMobileV1PostsIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/posts_controller.ts').default['destroy'], false>
}
type ApiMobileV1PostsIdLikePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/posts_controller.ts').default['like'], false>
}
type ApiMobileV1PostsIdReportPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/mobile/validators.ts')['mobileReportPostValidator']>>
  response: MakeTuyauResponse<import('../app/mobile/controllers/posts_controller.ts').default['report'], true>
}
type ApiMobileV1PostsIdRevealGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/posts_controller.ts').default['reveal'], false>
}
type ApiMobileV1PostsIdCommentsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/posts_controller.ts').default['comments'], false>
}
type ApiMobileV1ChannelsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/channels_controller.ts').default['index'], false>
}
type ApiMobileV1ChannelsIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/channels_controller.ts').default['show'], false>
}
type ApiMobileV1ChannelsIdJoinPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/channels_controller.ts').default['join'], false>
}
type ApiMobileV1ChannelsIdLeaveDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/channels_controller.ts').default['leave'], false>
}
type ApiMobileV1ChannelsIdMessagesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/channel_messages_controller.ts').default['index'], false>
}
type ApiMobileV1ChannelsIdMessagesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/mobile/validators.ts')['mobileSendMessageValidator']>>
  response: MakeTuyauResponse<import('../app/mobile/controllers/channel_messages_controller.ts').default['store'], true>
}
type ApiMobileV1ChannelsMessagesIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/channel_messages_controller.ts').default['destroy'], false>
}
type ApiMobileV1ChannelsMessagesIdReactionsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/mobile/validators.ts')['mobileReactionValidator']>>
  response: MakeTuyauResponse<import('../app/mobile/controllers/channel_messages_controller.ts').default['react'], true>
}
type ApiMobileV1SurveysGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/surveys_controller.ts').default['index'], false>
}
type ApiMobileV1SurveysIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/surveys_controller.ts').default['show'], false>
}
type ApiMobileV1SurveysIdSubmitPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/mobile/validators.ts')['mobileSurveySubmitValidator']>>
  response: MakeTuyauResponse<import('../app/mobile/controllers/surveys_controller.ts').default['submit'], true>
}
type ApiMobileV1NotificationsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/notifications_controller.ts').default['index'], false>
}
type ApiMobileV1NotificationsReadallPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/notifications_controller.ts').default['readAll'], false>
}
type ApiMobileV1NotificationsIdReadPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/notifications_controller.ts').default['read'], false>
}
type ApiMobileV1NotificationsIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/notifications_controller.ts').default['destroy'], false>
}
type ApiMobileV1AdminUsersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/admin_controller.ts').default['users'], false>
}
type ApiMobileV1AdminUsersIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/mobile/validators.ts')['mobileUpdateUserValidator']>>
  response: MakeTuyauResponse<import('../app/mobile/controllers/admin_controller.ts').default['updateUser'], true>
}
type ApiMobileV1AdminUsersIdBanPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/mobile/validators.ts')['mobileBanUserValidator']>>
  response: MakeTuyauResponse<import('../app/mobile/controllers/admin_controller.ts').default['banUser'], true>
}
type ApiMobileV1AdminUsersIdBanDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/admin_controller.ts').default['unbanUser'], false>
}
type ApiMobileV1AdminReportsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/admin_controller.ts').default['reports'], false>
}
type ApiMobileV1AdminReportsIdAcceptPut = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/admin_controller.ts').default['acceptReport'], false>
}
type ApiMobileV1AdminReportsIdRejectPut = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/admin_controller.ts').default['rejectReport'], false>
}
type ApiMobileV1AdminDeletedpostsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/admin_controller.ts').default['deletedPosts'], false>
}
type ApiMobileV1AdminDeletedpostsIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/mobile/controllers/admin_controller.ts').default['hardDelete'], false>
}
type DashboardGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/dashboard/controllers/dashboard_controller.ts').default['handle'], false>
}
type DashboardPostsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/dashboard/controllers/dashboard_controller.ts').default['list'], false>
}
type DashboardUsersGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/dashboard/validators.ts')['listUserValidator']>>
  response: MakeTuyauResponse<import('../app/dashboard/controllers/users_controller.ts').default['index'], true>
}
type DashboardUsersPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/dashboard/validators.ts')['createUserValidator']>>
  response: MakeTuyauResponse<import('../app/dashboard/controllers/users_controller.ts').default['store'], true>
}
type DashboardUsersIdPutPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/dashboard/validators.ts')['editUserValidator']>>
  response: MakeTuyauResponse<import('../app/dashboard/controllers/users_controller.ts').default['update'], true>
}
type DashboardUsersIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/dashboard/controllers/users_controller.ts').default['destroy'], false>
}
type DashboardUsersInvitePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/dashboard/validators.ts')['inviteUserValidator']>>
  response: MakeTuyauResponse<import('../app/dashboard/controllers/invite_controller.ts').default['handle'], true>
}
type DashboardUsersImpersonateIdPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/dashboard/controllers/impersonates_controller.ts').default['store'], false>
}
type DashboardUsersIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/dashboard/controllers/users_controller.ts').default['show'], false>
}
type DashboardSurveysAdminGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/dashboard/validators.ts')['listSurveyValidator']>>
  response: MakeTuyauResponse<import('../app/dashboard/controllers/surveys_controller.ts').default['index'], true>
}
type DashboardSurveysAdminPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/dashboard/validators.ts')['createSurveyValidator']>>
  response: MakeTuyauResponse<import('../app/dashboard/controllers/surveys_controller.ts').default['store'], true>
}
type DashboardSurveysAdminIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/dashboard/controllers/surveys_controller.ts').default['show'], false>
}
type DashboardSurveysAdminIdAnalyticsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/dashboard/controllers/surveys_controller.ts').default['analytics'], false>
}
type DashboardSurveysAdminQuestionsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/dashboard/validators.ts')['createQuestionValidator']>>
  response: MakeTuyauResponse<import('../app/dashboard/controllers/surveys_controller.ts').default['storeQuestion'], true>
}
type DashboardSurveysAdminIdQuestionsIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/dashboard/validators.ts')['updateQuestionValidator']>>
  response: MakeTuyauResponse<import('../app/dashboard/controllers/surveys_controller.ts').default['updateQuestion'], true>
}
type DashboardSurveysAdminIdQuestionsIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/dashboard/controllers/surveys_controller.ts').default['destroyQuestion'], false>
}
type DashboardSurveysAdminIdQuestionsIdAnswersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/dashboard/controllers/surveys_controller.ts').default['getQuestionAnswers'], false>
}
type DashboardSurveysAdminIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/dashboard/validators.ts')['updateSurveyValidator']>>
  response: MakeTuyauResponse<import('../app/dashboard/controllers/surveys_controller.ts').default['update'], true>
}
type DashboardSurveysAdminIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/dashboard/controllers/surveys_controller.ts').default['destroy'], false>
}
type DashboardAdminSettingsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/dashboard/controllers/admin_controller.ts').default['show'], false>
}
type DashboardAdminSettingsPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/dashboard/validators.ts')['editWebsiteSettingsValidator']>>
  response: MakeTuyauResponse<import('../app/dashboard/controllers/admin_controller.ts').default['handle'], true>
}
type DashboardAdminChannelsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/dashboard/controllers/channels_admin_controller.ts').default['index'], false>
}
type DashboardAdminRolesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/dashboard/controllers/roles_admin_controller.ts').default['index'], false>
}
type DashboardAdminRolesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/dashboard/validators.ts')['createRoleValidator']>>
  response: MakeTuyauResponse<import('../app/dashboard/controllers/roles_admin_controller.ts').default['store'], true>
}
type DashboardAdminRolesIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/dashboard/controllers/roles_admin_controller.ts').default['show'], false>
}
type DashboardAdminRolesIdPutPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/dashboard/validators.ts')['updateRoleValidator']>>
  response: MakeTuyauResponse<import('../app/dashboard/controllers/roles_admin_controller.ts').default['update'], true>
}
type DashboardAdminRolesIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/dashboard/controllers/roles_admin_controller.ts').default['destroy'], false>
}
type ChannelsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/channels/controllers/channels_controller.ts').default['index'], false>
}
type ChannelsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/channels/validators.ts')['createChannelValidator']>>
  response: MakeTuyauResponse<import('../app/channels/controllers/channels_controller.ts').default['store'], true>
}
type ChannelsIdTypingGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/channels/controllers/channels_controller.ts').default['typing'], false>
}
type ChannelsIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/channels/controllers/channels_controller.ts').default['show'], false>
}
type ChannelsIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/channels/validators.ts')['createChannelValidator']>>
  response: MakeTuyauResponse<import('../app/channels/controllers/channels_controller.ts').default['update'], true>
}
type ChannelsIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/channels/controllers/channels_controller.ts').default['destroy'], false>
}
type ChannelsIdJoinPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/channels/controllers/channels_controller.ts').default['join'], false>
}
type ChannelsIdLeaveDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/channels/controllers/channels_controller.ts').default['leave'], false>
}
type ChannelsIdMessagesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/channels/validators.ts')['createMessageValidator']>>
  response: MakeTuyauResponse<import('../app/channels/controllers/channel_messages_controller.ts').default['store'], true>
}
type ChannelsIdMessagesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/channels/controllers/channel_messages_controller.ts').default['index'], false>
}
type ChannelsMessagesIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/channels/controllers/channel_messages_controller.ts').default['destroy'], false>
}
type ChannelsMessagesIdReactionsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/channels/validators.ts')['createReactionValidator']>>
  response: MakeTuyauResponse<import('../app/channels/controllers/channel_messages_controller.ts').default['react'], true>
}
type PostsIdReportPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/post/validators/post_report_validator.ts')['createPostReportValidator']>>
  response: MakeTuyauResponse<import('../app/post/controllers/post_report_controller.ts').default['store'], true>
}
type DashboardAdminReportsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/post/controllers/post_report_controller.ts').default['index'], false>
}
type DashboardAdminReportsIdRejectPut = {
  request: unknown
  response: MakeTuyauResponse<import('../app/post/controllers/post_report_controller.ts').default['reject'], false>
}
type DashboardAdminReportsIdAcceptPut = {
  request: unknown
  response: MakeTuyauResponse<import('../app/post/controllers/post_report_controller.ts').default['accept'], false>
}
type DashboardAdminDeletedpostsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/post/controllers/deleted_post_controller.ts').default['index'], false>
}
type DashboardAdminDeletedpostsIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/post/controllers/deleted_post_controller.ts').default['destroy'], false>
}
type SettingsProfilePut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/dashboard/validators.ts')['updateProfileValidator']>>
  response: MakeTuyauResponse<import('../app/users/controllers/profile_controller.ts').default['handle'], true>
}
type SettingsProfileGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/users/controllers/profile_controller.ts').default['show'], false>
}
type SettingsTokensGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/users/controllers/tokens_controller.ts').default['index'], false>
}
type SettingsTokensIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/users/controllers/tokens_controller.ts').default['destroy'], false>
}
type ApiTokensPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/dashboard/validators.ts')['createTokenValidator']>>
  response: MakeTuyauResponse<import('../app/users/controllers/tokens_controller.ts').default['store'], true>
}
type SettingsPasswordPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/dashboard/validators.ts')['updatePasswordValidator']>>
  response: MakeTuyauResponse<import('../app/users/controllers/password_controller.ts').default['handle'], true>
}
type SettingsPasswordGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/users/controllers/password_controller.ts').default['show'], false>
}
type UsersNotificationsIdReadPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/users/controllers/notifications_controller.ts').default['read'], false>
}
type UsersNotificationsIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/users/controllers/notifications_controller.ts').default['destroy'], false>
}
export interface ApiDefinition {
  'maintenance': {
    '$url': {
    };
    '$get': MaintenanceGetHead;
    '$head': MaintenanceGetHead;
  };
  'mentions-legales': {
    '$url': {
    };
    '$get': MentionsLegalesGetHead;
    '$head': MentionsLegalesGetHead;
  };
  'cgu': {
    '$url': {
    };
    '$get': CguGetHead;
    '$head': CguGetHead;
  };
  'politique-confidentialite': {
    '$url': {
    };
    '$get': PolitiqueConfidentialiteGetHead;
    '$head': PolitiqueConfidentialiteGetHead;
  };
  'login': {
    '$url': {
    };
    '$get': LoginGetHead;
    '$head': LoginGetHead;
    '$post': LoginPost;
  };
  'logout': {
    '$url': {
    };
    '$get': LogoutGetHead;
    '$head': LogoutGetHead;
  };
  'sign-up': {
    '$url': {
    };
    '$get': SignUpGetHead;
    '$head': SignUpGetHead;
    '$post': SignUpPost;
  };
  'forgot-password': {
    '$url': {
    };
    '$get': ForgotPasswordGetHead;
    '$head': ForgotPasswordGetHead;
    '$post': ForgotPasswordPost;
  };
  'reset-password': {
    ':token': {
      '$url': {
      };
      '$get': ResetpasswordIdGetHead;
      '$head': ResetpasswordIdGetHead;
      '$post': ResetpasswordIdPost;
    };
  };
  'dashboard': {
    'publicities': {
      '$url': {
      };
      '$get': DashboardPublicitiesGetHead;
      '$head': DashboardPublicitiesGetHead;
      'create': {
        '$url': {
        };
        '$get': DashboardPublicitiesCreateGetHead;
        '$head': DashboardPublicitiesCreateGetHead;
      };
      '$post': DashboardPublicitiesPost;
      ':uuid': {
        'edit': {
          '$url': {
          };
          '$get': DashboardPublicitiesIdEditGetHead;
          '$head': DashboardPublicitiesIdEditGetHead;
        };
        '$url': {
        };
        '$put': DashboardPublicitiesIdPut;
        '$delete': DashboardPublicitiesIdDelete;
        'stats': {
          '$url': {
          };
          '$get': DashboardPublicitiesIdStatsGetHead;
          '$head': DashboardPublicitiesIdStatsGetHead;
        };
      };
      'admin': {
        '$url': {
        };
        '$get': DashboardPublicitiesAdminGetHead;
        '$head': DashboardPublicitiesAdminGetHead;
        ':uuid': {
          'approve': {
            '$url': {
            };
            '$post': DashboardPublicitiesAdminIdApprovePost;
          };
          'reject': {
            '$url': {
            };
            '$post': DashboardPublicitiesAdminIdRejectPost;
          };
        };
      };
    };
    'pub': {
      ':uuid': {
        '$url': {
        };
        '$get': DashboardPubIdGetHead;
        '$head': DashboardPubIdGetHead;
      };
    };
    '$url': {
    };
    '$get': DashboardGetHead;
    '$head': DashboardGetHead;
    'posts': {
      '$url': {
      };
      '$get': DashboardPostsGetHead;
      '$head': DashboardPostsGetHead;
    };
    'users': {
      '$url': {
      };
      '$get': DashboardUsersGetHead;
      '$head': DashboardUsersGetHead;
      '$post': DashboardUsersPost;
      ':id': {
        '$url': {
        };
        '$put': DashboardUsersIdPutPatch;
        '$patch': DashboardUsersIdPutPatch;
        '$delete': DashboardUsersIdDelete;
      };
      'invite': {
        '$url': {
        };
        '$post': DashboardUsersInvitePost;
      };
      'impersonate': {
        ':id': {
          '$url': {
          };
          '$post': DashboardUsersImpersonateIdPost;
        };
      };
      ':uuid': {
        '$url': {
        };
        '$get': DashboardUsersIdGetHead;
        '$head': DashboardUsersIdGetHead;
      };
    };
    'surveys': {
      'admin': {
        '$url': {
        };
        '$get': DashboardSurveysAdminGetHead;
        '$head': DashboardSurveysAdminGetHead;
        '$post': DashboardSurveysAdminPost;
        ':uuid': {
          '$url': {
          };
          '$get': DashboardSurveysAdminIdGetHead;
          '$head': DashboardSurveysAdminIdGetHead;
          'analytics': {
            '$url': {
            };
            '$get': DashboardSurveysAdminIdAnalyticsGetHead;
            '$head': DashboardSurveysAdminIdAnalyticsGetHead;
          };
          'questions': {
            ':questionUuid': {
              '$url': {
              };
              '$put': DashboardSurveysAdminIdQuestionsIdPut;
              '$delete': DashboardSurveysAdminIdQuestionsIdDelete;
              'answers': {
                '$url': {
                };
                '$get': DashboardSurveysAdminIdQuestionsIdAnswersGetHead;
                '$head': DashboardSurveysAdminIdQuestionsIdAnswersGetHead;
              };
            };
          };
          '$put': DashboardSurveysAdminIdPut;
          '$delete': DashboardSurveysAdminIdDelete;
        };
        'questions': {
          '$url': {
          };
          '$post': DashboardSurveysAdminQuestionsPost;
        };
      };
    };
    'admin': {
      'settings': {
        '$url': {
        };
        '$get': DashboardAdminSettingsGetHead;
        '$head': DashboardAdminSettingsGetHead;
        '$put': DashboardAdminSettingsPut;
      };
      'channels': {
        '$url': {
        };
        '$get': DashboardAdminChannelsGetHead;
        '$head': DashboardAdminChannelsGetHead;
      };
      'roles': {
        '$url': {
        };
        '$get': DashboardAdminRolesGetHead;
        '$head': DashboardAdminRolesGetHead;
        '$post': DashboardAdminRolesPost;
        ':id': {
          '$url': {
          };
          '$get': DashboardAdminRolesIdGetHead;
          '$head': DashboardAdminRolesIdGetHead;
          '$put': DashboardAdminRolesIdPutPatch;
          '$patch': DashboardAdminRolesIdPutPatch;
          '$delete': DashboardAdminRolesIdDelete;
        };
      };
      'reports': {
        '$url': {
        };
        '$get': DashboardAdminReportsGetHead;
        '$head': DashboardAdminReportsGetHead;
        ':uuid': {
          'reject': {
            '$url': {
            };
            '$put': DashboardAdminReportsIdRejectPut;
          };
          'accept': {
            '$url': {
            };
            '$put': DashboardAdminReportsIdAcceptPut;
          };
        };
      };
      'deleted-posts': {
        '$url': {
        };
        '$get': DashboardAdminDeletedpostsGetHead;
        '$head': DashboardAdminDeletedpostsGetHead;
        ':uuid': {
          '$url': {
          };
          '$delete': DashboardAdminDeletedpostsIdDelete;
        };
      };
    };
  };
  'api': {
    'evt': {
      'collect': {
        '$url': {
        };
        '$post': ApiEvtCollectPost;
      };
    };
    'mobile': {
      'v1': {
        'auth': {
          'login': {
            '$url': {
            };
            '$post': ApiMobileV1AuthLoginPost;
          };
          'register': {
            '$url': {
            };
            '$post': ApiMobileV1AuthRegisterPost;
          };
          'forgot-password': {
            '$url': {
            };
            '$post': ApiMobileV1AuthForgotpasswordPost;
          };
          'me': {
            '$url': {
            };
            '$get': ApiMobileV1AuthMeGetHead;
            '$head': ApiMobileV1AuthMeGetHead;
          };
          'logout': {
            '$url': {
            };
            '$delete': ApiMobileV1AuthLogoutDelete;
          };
        };
        'push': {
          'register': {
            '$url': {
            };
            '$post': ApiMobileV1PushRegisterPost;
          };
          'unregister': {
            '$url': {
            };
            '$delete': ApiMobileV1PushUnregisterDelete;
          };
        };
        'posts': {
          '$url': {
          };
          '$get': ApiMobileV1PostsGetHead;
          '$head': ApiMobileV1PostsGetHead;
          '$post': ApiMobileV1PostsPost;
          ':uuid': {
            '$url': {
            };
            '$get': ApiMobileV1PostsIdGetHead;
            '$head': ApiMobileV1PostsIdGetHead;
            '$delete': ApiMobileV1PostsIdDelete;
            'like': {
              '$url': {
              };
              '$post': ApiMobileV1PostsIdLikePost;
            };
            'report': {
              '$url': {
              };
              '$post': ApiMobileV1PostsIdReportPost;
            };
            'reveal': {
              '$url': {
              };
              '$get': ApiMobileV1PostsIdRevealGetHead;
              '$head': ApiMobileV1PostsIdRevealGetHead;
            };
            'comments': {
              '$url': {
              };
              '$get': ApiMobileV1PostsIdCommentsGetHead;
              '$head': ApiMobileV1PostsIdCommentsGetHead;
            };
          };
        };
        'channels': {
          '$url': {
          };
          '$get': ApiMobileV1ChannelsGetHead;
          '$head': ApiMobileV1ChannelsGetHead;
          ':uuid': {
            '$url': {
            };
            '$get': ApiMobileV1ChannelsIdGetHead;
            '$head': ApiMobileV1ChannelsIdGetHead;
            'join': {
              '$url': {
              };
              '$post': ApiMobileV1ChannelsIdJoinPost;
            };
            'leave': {
              '$url': {
              };
              '$delete': ApiMobileV1ChannelsIdLeaveDelete;
            };
            'messages': {
              '$url': {
              };
              '$get': ApiMobileV1ChannelsIdMessagesGetHead;
              '$head': ApiMobileV1ChannelsIdMessagesGetHead;
              '$post': ApiMobileV1ChannelsIdMessagesPost;
            };
          };
          'messages': {
            ':uuid': {
              '$url': {
              };
              '$delete': ApiMobileV1ChannelsMessagesIdDelete;
              'reactions': {
                '$url': {
                };
                '$post': ApiMobileV1ChannelsMessagesIdReactionsPost;
              };
            };
          };
        };
        'surveys': {
          '$url': {
          };
          '$get': ApiMobileV1SurveysGetHead;
          '$head': ApiMobileV1SurveysGetHead;
          ':uuid': {
            '$url': {
            };
            '$get': ApiMobileV1SurveysIdGetHead;
            '$head': ApiMobileV1SurveysIdGetHead;
            'submit': {
              '$url': {
              };
              '$post': ApiMobileV1SurveysIdSubmitPost;
            };
          };
        };
        'notifications': {
          '$url': {
          };
          '$get': ApiMobileV1NotificationsGetHead;
          '$head': ApiMobileV1NotificationsGetHead;
          'read-all': {
            '$url': {
            };
            '$post': ApiMobileV1NotificationsReadallPost;
          };
          ':uuid': {
            'read': {
              '$url': {
              };
              '$post': ApiMobileV1NotificationsIdReadPost;
            };
            '$url': {
            };
            '$delete': ApiMobileV1NotificationsIdDelete;
          };
        };
        'admin': {
          'users': {
            '$url': {
            };
            '$get': ApiMobileV1AdminUsersGetHead;
            '$head': ApiMobileV1AdminUsersGetHead;
            ':uuid': {
              '$url': {
              };
              '$put': ApiMobileV1AdminUsersIdPut;
              'ban': {
                '$url': {
                };
                '$post': ApiMobileV1AdminUsersIdBanPost;
                '$delete': ApiMobileV1AdminUsersIdBanDelete;
              };
            };
          };
          'reports': {
            '$url': {
            };
            '$get': ApiMobileV1AdminReportsGetHead;
            '$head': ApiMobileV1AdminReportsGetHead;
            ':uuid': {
              'accept': {
                '$url': {
                };
                '$put': ApiMobileV1AdminReportsIdAcceptPut;
              };
              'reject': {
                '$url': {
                };
                '$put': ApiMobileV1AdminReportsIdRejectPut;
              };
            };
          };
          'deleted-posts': {
            '$url': {
            };
            '$get': ApiMobileV1AdminDeletedpostsGetHead;
            '$head': ApiMobileV1AdminDeletedpostsGetHead;
            ':uuid': {
              '$url': {
              };
              '$delete': ApiMobileV1AdminDeletedpostsIdDelete;
            };
          };
        };
      };
    };
    'tokens': {
      '$url': {
      };
      '$post': ApiTokensPost;
    };
  };
  'channels': {
    '$url': {
    };
    '$get': ChannelsGetHead;
    '$head': ChannelsGetHead;
    '$post': ChannelsPost;
    ':uuid': {
      'typing': {
        '$url': {
        };
        '$get': ChannelsIdTypingGetHead;
        '$head': ChannelsIdTypingGetHead;
      };
      '$url': {
      };
      '$get': ChannelsIdGetHead;
      '$head': ChannelsIdGetHead;
      '$put': ChannelsIdPut;
      '$delete': ChannelsIdDelete;
      'join': {
        '$url': {
        };
        '$post': ChannelsIdJoinPost;
      };
      'leave': {
        '$url': {
        };
        '$delete': ChannelsIdLeaveDelete;
      };
    };
    ':channel_uuid': {
      'messages': {
        '$url': {
        };
        '$post': ChannelsIdMessagesPost;
        '$get': ChannelsIdMessagesGetHead;
        '$head': ChannelsIdMessagesGetHead;
      };
    };
    'messages': {
      ':uuid': {
        '$url': {
        };
        '$delete': ChannelsMessagesIdDelete;
        'reactions': {
          '$url': {
          };
          '$post': ChannelsMessagesIdReactionsPost;
        };
      };
    };
  };
  'posts': {
    ':uuid': {
      'report': {
        '$url': {
        };
        '$post': PostsIdReportPost;
      };
    };
  };
  'settings': {
    'profile': {
      '$url': {
      };
      '$put': SettingsProfilePut;
      '$get': SettingsProfileGetHead;
      '$head': SettingsProfileGetHead;
    };
    'tokens': {
      '$url': {
      };
      '$get': SettingsTokensGetHead;
      '$head': SettingsTokensGetHead;
      ':id': {
        '$url': {
        };
        '$delete': SettingsTokensIdDelete;
      };
    };
    'password': {
      '$url': {
      };
      '$put': SettingsPasswordPut;
      '$get': SettingsPasswordGetHead;
      '$head': SettingsPasswordGetHead;
    };
  };
  'users': {
    'notifications': {
      ':uuid': {
        'read': {
          '$url': {
          };
          '$post': UsersNotificationsIdReadPost;
        };
        '$url': {
        };
        '$delete': UsersNotificationsIdDelete;
      };
    };
  };
}
const routes = [
  {
    params: ["*"],
    name: 'drive.fs.serve',
    path: '/uploads/*',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'home.show',
    path: '/',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'maintenance.show',
    path: '/maintenance',
    method: ["GET","HEAD"],
    types: {} as MaintenanceGetHead,
  },
  {
    params: [],
    name: 'legal.mentions',
    path: '/mentions-legales',
    method: ["GET","HEAD"],
    types: {} as MentionsLegalesGetHead,
  },
  {
    params: [],
    name: 'legal.cgu',
    path: '/cgu',
    method: ["GET","HEAD"],
    types: {} as CguGetHead,
  },
  {
    params: [],
    name: 'legal.privacy',
    path: '/politique-confidentialite',
    method: ["GET","HEAD"],
    types: {} as PolitiqueConfidentialiteGetHead,
  },
  {
    params: [],
    name: 'auth.sign_in.show',
    path: '/login',
    method: ["GET","HEAD"],
    types: {} as LoginGetHead,
  },
  {
    params: [],
    name: 'auth.sign_out.show',
    path: '/logout',
    method: ["GET","HEAD"],
    types: {} as LogoutGetHead,
  },
  {
    params: [],
    name: 'auth.sign_up.show',
    path: '/sign-up',
    method: ["GET","HEAD"],
    types: {} as SignUpGetHead,
  },
  {
    params: [],
    name: 'auth.sign_up.handle',
    path: '/sign-up',
    method: ["POST"],
    types: {} as SignUpPost,
  },
  {
    params: [],
    name: 'auth.forgot_password.show',
    path: '/forgot-password',
    method: ["GET","HEAD"],
    types: {} as ForgotPasswordGetHead,
  },
  {
    params: [],
    name: 'auth.forgot_password.handle',
    path: '/forgot-password',
    method: ["POST"],
    types: {} as ForgotPasswordPost,
  },
  {
    params: ["token"],
    name: 'auth.reset_password.show',
    path: '/reset-password/:token',
    method: ["GET","HEAD"],
    types: {} as ResetpasswordIdGetHead,
  },
  {
    params: ["token"],
    name: 'auth.reset_password.handle',
    path: '/reset-password/:token',
    method: ["POST"],
    types: {} as ResetpasswordIdPost,
  },
  {
    params: [],
    name: 'publicity.index',
    path: '/dashboard/publicities',
    method: ["GET","HEAD"],
    types: {} as DashboardPublicitiesGetHead,
  },
  {
    params: [],
    name: 'publicity.create',
    path: '/dashboard/publicities/create',
    method: ["GET","HEAD"],
    types: {} as DashboardPublicitiesCreateGetHead,
  },
  {
    params: [],
    name: 'publicity.store',
    path: '/dashboard/publicities',
    method: ["POST"],
    types: {} as DashboardPublicitiesPost,
  },
  {
    params: ["uuid"],
    name: 'publicity.edit',
    path: '/dashboard/publicities/:uuid/edit',
    method: ["GET","HEAD"],
    types: {} as DashboardPublicitiesIdEditGetHead,
  },
  {
    params: ["uuid"],
    name: 'publicity.update',
    path: '/dashboard/publicities/:uuid',
    method: ["PUT"],
    types: {} as DashboardPublicitiesIdPut,
  },
  {
    params: ["uuid"],
    name: 'publicity.destroy',
    path: '/dashboard/publicities/:uuid',
    method: ["DELETE"],
    types: {} as DashboardPublicitiesIdDelete,
  },
  {
    params: ["uuid"],
    name: 'publicity.stats',
    path: '/dashboard/publicities/:uuid/stats',
    method: ["GET","HEAD"],
    types: {} as DashboardPublicitiesIdStatsGetHead,
  },
  {
    params: [],
    name: 'publicity.admin.index',
    path: '/dashboard/publicities/admin',
    method: ["GET","HEAD"],
    types: {} as DashboardPublicitiesAdminGetHead,
  },
  {
    params: ["uuid"],
    name: 'publicity.admin.approve',
    path: '/dashboard/publicities/admin/:uuid/approve',
    method: ["POST"],
    types: {} as DashboardPublicitiesAdminIdApprovePost,
  },
  {
    params: ["uuid"],
    name: 'publicity.admin.reject',
    path: '/dashboard/publicities/admin/:uuid/reject',
    method: ["POST"],
    types: {} as DashboardPublicitiesAdminIdRejectPost,
  },
  {
    params: ["uuid"],
    name: 'publicity.show',
    path: '/dashboard/pub/:uuid',
    method: ["GET","HEAD"],
    types: {} as DashboardPubIdGetHead,
  },
  {
    params: [],
    name: 'publicity.track',
    path: '/api/evt/collect',
    method: ["POST"],
    types: {} as ApiEvtCollectPost,
  },
  {
    params: [],
    name: 'mobile.auth.login',
    path: '/api/mobile/v1/auth/login',
    method: ["POST"],
    types: {} as ApiMobileV1AuthLoginPost,
  },
  {
    params: [],
    name: 'mobile.auth.register',
    path: '/api/mobile/v1/auth/register',
    method: ["POST"],
    types: {} as ApiMobileV1AuthRegisterPost,
  },
  {
    params: [],
    name: 'mobile.auth.forgotPassword',
    path: '/api/mobile/v1/auth/forgot-password',
    method: ["POST"],
    types: {} as ApiMobileV1AuthForgotpasswordPost,
  },
  {
    params: [],
    name: 'mobile.auth.me',
    path: '/api/mobile/v1/auth/me',
    method: ["GET","HEAD"],
    types: {} as ApiMobileV1AuthMeGetHead,
  },
  {
    params: [],
    name: 'mobile.auth.logout',
    path: '/api/mobile/v1/auth/logout',
    method: ["DELETE"],
    types: {} as ApiMobileV1AuthLogoutDelete,
  },
  {
    params: [],
    name: 'mobile.push.register',
    path: '/api/mobile/v1/push/register',
    method: ["POST"],
    types: {} as ApiMobileV1PushRegisterPost,
  },
  {
    params: [],
    name: 'mobile.push.unregister',
    path: '/api/mobile/v1/push/unregister',
    method: ["DELETE"],
    types: {} as ApiMobileV1PushUnregisterDelete,
  },
  {
    params: [],
    name: 'mobile.posts.index',
    path: '/api/mobile/v1/posts',
    method: ["GET","HEAD"],
    types: {} as ApiMobileV1PostsGetHead,
  },
  {
    params: [],
    name: 'mobile.posts.store',
    path: '/api/mobile/v1/posts',
    method: ["POST"],
    types: {} as ApiMobileV1PostsPost,
  },
  {
    params: ["uuid"],
    name: 'mobile.posts.show',
    path: '/api/mobile/v1/posts/:uuid',
    method: ["GET","HEAD"],
    types: {} as ApiMobileV1PostsIdGetHead,
  },
  {
    params: ["uuid"],
    name: 'mobile.posts.destroy',
    path: '/api/mobile/v1/posts/:uuid',
    method: ["DELETE"],
    types: {} as ApiMobileV1PostsIdDelete,
  },
  {
    params: ["uuid"],
    name: 'mobile.posts.like',
    path: '/api/mobile/v1/posts/:uuid/like',
    method: ["POST"],
    types: {} as ApiMobileV1PostsIdLikePost,
  },
  {
    params: ["uuid"],
    name: 'mobile.posts.report',
    path: '/api/mobile/v1/posts/:uuid/report',
    method: ["POST"],
    types: {} as ApiMobileV1PostsIdReportPost,
  },
  {
    params: ["uuid"],
    name: 'mobile.posts.reveal',
    path: '/api/mobile/v1/posts/:uuid/reveal',
    method: ["GET","HEAD"],
    types: {} as ApiMobileV1PostsIdRevealGetHead,
  },
  {
    params: ["uuid"],
    name: 'mobile.posts.comments',
    path: '/api/mobile/v1/posts/:uuid/comments',
    method: ["GET","HEAD"],
    types: {} as ApiMobileV1PostsIdCommentsGetHead,
  },
  {
    params: [],
    name: 'mobile.channels.index',
    path: '/api/mobile/v1/channels',
    method: ["GET","HEAD"],
    types: {} as ApiMobileV1ChannelsGetHead,
  },
  {
    params: ["uuid"],
    name: 'mobile.channels.show',
    path: '/api/mobile/v1/channels/:uuid',
    method: ["GET","HEAD"],
    types: {} as ApiMobileV1ChannelsIdGetHead,
  },
  {
    params: ["uuid"],
    name: 'mobile.channels.join',
    path: '/api/mobile/v1/channels/:uuid/join',
    method: ["POST"],
    types: {} as ApiMobileV1ChannelsIdJoinPost,
  },
  {
    params: ["uuid"],
    name: 'mobile.channels.leave',
    path: '/api/mobile/v1/channels/:uuid/leave',
    method: ["DELETE"],
    types: {} as ApiMobileV1ChannelsIdLeaveDelete,
  },
  {
    params: ["uuid"],
    name: 'mobile.channels.messages.index',
    path: '/api/mobile/v1/channels/:uuid/messages',
    method: ["GET","HEAD"],
    types: {} as ApiMobileV1ChannelsIdMessagesGetHead,
  },
  {
    params: ["uuid"],
    name: 'mobile.channels.messages.store',
    path: '/api/mobile/v1/channels/:uuid/messages',
    method: ["POST"],
    types: {} as ApiMobileV1ChannelsIdMessagesPost,
  },
  {
    params: ["uuid"],
    name: 'mobile.channels.messages.destroy',
    path: '/api/mobile/v1/channels/messages/:uuid',
    method: ["DELETE"],
    types: {} as ApiMobileV1ChannelsMessagesIdDelete,
  },
  {
    params: ["uuid"],
    name: 'mobile.channels.messages.react',
    path: '/api/mobile/v1/channels/messages/:uuid/reactions',
    method: ["POST"],
    types: {} as ApiMobileV1ChannelsMessagesIdReactionsPost,
  },
  {
    params: [],
    name: 'mobile.surveys.index',
    path: '/api/mobile/v1/surveys',
    method: ["GET","HEAD"],
    types: {} as ApiMobileV1SurveysGetHead,
  },
  {
    params: ["uuid"],
    name: 'mobile.surveys.show',
    path: '/api/mobile/v1/surveys/:uuid',
    method: ["GET","HEAD"],
    types: {} as ApiMobileV1SurveysIdGetHead,
  },
  {
    params: ["uuid"],
    name: 'mobile.surveys.submit',
    path: '/api/mobile/v1/surveys/:uuid/submit',
    method: ["POST"],
    types: {} as ApiMobileV1SurveysIdSubmitPost,
  },
  {
    params: [],
    name: 'mobile.notifications.index',
    path: '/api/mobile/v1/notifications',
    method: ["GET","HEAD"],
    types: {} as ApiMobileV1NotificationsGetHead,
  },
  {
    params: [],
    name: 'mobile.notifications.readAll',
    path: '/api/mobile/v1/notifications/read-all',
    method: ["POST"],
    types: {} as ApiMobileV1NotificationsReadallPost,
  },
  {
    params: ["uuid"],
    name: 'mobile.notifications.read',
    path: '/api/mobile/v1/notifications/:uuid/read',
    method: ["POST"],
    types: {} as ApiMobileV1NotificationsIdReadPost,
  },
  {
    params: ["uuid"],
    name: 'mobile.notifications.destroy',
    path: '/api/mobile/v1/notifications/:uuid',
    method: ["DELETE"],
    types: {} as ApiMobileV1NotificationsIdDelete,
  },
  {
    params: [],
    name: 'mobile.admin.users',
    path: '/api/mobile/v1/admin/users',
    method: ["GET","HEAD"],
    types: {} as ApiMobileV1AdminUsersGetHead,
  },
  {
    params: ["uuid"],
    name: 'mobile.admin.updateUser',
    path: '/api/mobile/v1/admin/users/:uuid',
    method: ["PUT"],
    types: {} as ApiMobileV1AdminUsersIdPut,
  },
  {
    params: ["uuid"],
    name: 'mobile.admin.banUser',
    path: '/api/mobile/v1/admin/users/:uuid/ban',
    method: ["POST"],
    types: {} as ApiMobileV1AdminUsersIdBanPost,
  },
  {
    params: ["uuid"],
    name: 'mobile.admin.unbanUser',
    path: '/api/mobile/v1/admin/users/:uuid/ban',
    method: ["DELETE"],
    types: {} as ApiMobileV1AdminUsersIdBanDelete,
  },
  {
    params: [],
    name: 'mobile.admin.reports',
    path: '/api/mobile/v1/admin/reports',
    method: ["GET","HEAD"],
    types: {} as ApiMobileV1AdminReportsGetHead,
  },
  {
    params: ["uuid"],
    name: 'mobile.admin.acceptReport',
    path: '/api/mobile/v1/admin/reports/:uuid/accept',
    method: ["PUT"],
    types: {} as ApiMobileV1AdminReportsIdAcceptPut,
  },
  {
    params: ["uuid"],
    name: 'mobile.admin.rejectReport',
    path: '/api/mobile/v1/admin/reports/:uuid/reject',
    method: ["PUT"],
    types: {} as ApiMobileV1AdminReportsIdRejectPut,
  },
  {
    params: [],
    name: 'mobile.admin.deletedPosts',
    path: '/api/mobile/v1/admin/deleted-posts',
    method: ["GET","HEAD"],
    types: {} as ApiMobileV1AdminDeletedpostsGetHead,
  },
  {
    params: ["uuid"],
    name: 'mobile.admin.hardDelete',
    path: '/api/mobile/v1/admin/deleted-posts/:uuid',
    method: ["DELETE"],
    types: {} as ApiMobileV1AdminDeletedpostsIdDelete,
  },
  {
    params: [],
    name: 'dashboard.show',
    path: '/dashboard',
    method: ["GET","HEAD"],
    types: {} as DashboardGetHead,
  },
  {
    params: [],
    name: 'dashboard.posts',
    path: '/dashboard/posts',
    method: ["GET","HEAD"],
    types: {} as DashboardPostsGetHead,
  },
  {
    params: [],
    name: 'users.index',
    path: '/dashboard/users',
    method: ["GET","HEAD"],
    types: {} as DashboardUsersGetHead,
  },
  {
    params: [],
    name: 'users.store',
    path: '/dashboard/users',
    method: ["POST"],
    types: {} as DashboardUsersPost,
  },
  {
    params: ["id"],
    name: 'users.update',
    path: '/dashboard/users/:id',
    method: ["PUT","PATCH"],
    types: {} as DashboardUsersIdPutPatch,
  },
  {
    params: ["id"],
    name: 'users.destroy',
    path: '/dashboard/users/:id',
    method: ["DELETE"],
    types: {} as DashboardUsersIdDelete,
  },
  {
    params: [],
    name: 'surveys.index',
    path: '/dashboard/surveys/admin',
    method: ["GET","HEAD"],
    types: {} as DashboardSurveysAdminGetHead,
  },
  {
    params: [],
    name: 'surveys.store',
    path: '/dashboard/surveys/admin',
    method: ["POST"],
    types: {} as DashboardSurveysAdminPost,
  },
  {
    params: ["uuid"],
    name: 'surveys.show.admin',
    path: '/dashboard/surveys/admin/:uuid',
    method: ["GET","HEAD"],
    types: {} as DashboardSurveysAdminIdGetHead,
  },
  {
    params: ["uuid"],
    name: 'surveys.analytics',
    path: '/dashboard/surveys/admin/:uuid/analytics',
    method: ["GET","HEAD"],
    types: {} as DashboardSurveysAdminIdAnalyticsGetHead,
  },
  {
    params: [],
    name: 'surveys.storeQuestion',
    path: '/dashboard/surveys/admin/questions',
    method: ["POST"],
    types: {} as DashboardSurveysAdminQuestionsPost,
  },
  {
    params: ["uuid","questionUuid"],
    name: 'surveys.updateQuestion.admin',
    path: '/dashboard/surveys/admin/:uuid/questions/:questionUuid',
    method: ["PUT"],
    types: {} as DashboardSurveysAdminIdQuestionsIdPut,
  },
  {
    params: ["uuid","questionUuid"],
    name: 'surveys.destroyQuestion.admin',
    path: '/dashboard/surveys/admin/:uuid/questions/:questionUuid',
    method: ["DELETE"],
    types: {} as DashboardSurveysAdminIdQuestionsIdDelete,
  },
  {
    params: ["uuid","questionUuid"],
    name: 'surveys.questionAnswers.admin',
    path: '/dashboard/surveys/admin/:uuid/questions/:questionUuid/answers',
    method: ["GET","HEAD"],
    types: {} as DashboardSurveysAdminIdQuestionsIdAnswersGetHead,
  },
  {
    params: ["uuid"],
    name: 'surveys.update',
    path: '/dashboard/surveys/admin/:uuid',
    method: ["PUT"],
    types: {} as DashboardSurveysAdminIdPut,
  },
  {
    params: ["uuid"],
    name: 'surveys.destroy',
    path: '/dashboard/surveys/admin/:uuid',
    method: ["DELETE"],
    types: {} as DashboardSurveysAdminIdDelete,
  },
  {
    params: [],
    name: 'admin.settings.show',
    path: '/dashboard/admin/settings',
    method: ["GET","HEAD"],
    types: {} as DashboardAdminSettingsGetHead,
  },
  {
    params: [],
    name: 'admin.settings.update',
    path: '/dashboard/admin/settings',
    method: ["PUT"],
    types: {} as DashboardAdminSettingsPut,
  },
  {
    params: [],
    name: 'admin.channels.index',
    path: '/dashboard/admin/channels',
    method: ["GET","HEAD"],
    types: {} as DashboardAdminChannelsGetHead,
  },
  {
    params: [],
    name: 'admin_roles.index',
    path: '/dashboard/admin/roles',
    method: ["GET","HEAD"],
    types: {} as DashboardAdminRolesGetHead,
  },
  {
    params: [],
    name: 'admin_roles.create',
    path: '/dashboard/admin/roles/create',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'admin_roles.store',
    path: '/dashboard/admin/roles',
    method: ["POST"],
    types: {} as DashboardAdminRolesPost,
  },
  {
    params: ["id"],
    name: 'admin_roles.show',
    path: '/dashboard/admin/roles/:id',
    method: ["GET","HEAD"],
    types: {} as DashboardAdminRolesIdGetHead,
  },
  {
    params: ["id"],
    name: 'admin_roles.edit',
    path: '/dashboard/admin/roles/:id/edit',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: 'admin_roles.update',
    path: '/dashboard/admin/roles/:id',
    method: ["PUT","PATCH"],
    types: {} as DashboardAdminRolesIdPutPatch,
  },
  {
    params: ["id"],
    name: 'admin_roles.destroy',
    path: '/dashboard/admin/roles/:id',
    method: ["DELETE"],
    types: {} as DashboardAdminRolesIdDelete,
  },
  {
    params: [],
    name: 'channels.index',
    path: '/channels',
    method: ["GET","HEAD"],
    types: {} as ChannelsGetHead,
  },
  {
    params: [],
    name: 'channels.store',
    path: '/channels',
    method: ["POST"],
    types: {} as ChannelsPost,
  },
  {
    params: ["uuid"],
    name: 'channels.typing',
    path: '/channels/:uuid/typing',
    method: ["GET","HEAD"],
    types: {} as ChannelsIdTypingGetHead,
  },
  {
    params: ["uuid"],
    name: 'channels.show',
    path: '/channels/:uuid',
    method: ["GET","HEAD"],
    types: {} as ChannelsIdGetHead,
  },
  {
    params: ["uuid"],
    name: 'channels.update',
    path: '/channels/:uuid',
    method: ["PUT"],
    types: {} as ChannelsIdPut,
  },
  {
    params: ["uuid"],
    name: 'channels.destroy',
    path: '/channels/:uuid',
    method: ["DELETE"],
    types: {} as ChannelsIdDelete,
  },
  {
    params: ["uuid"],
    name: 'channels.join',
    path: '/channels/:uuid/join',
    method: ["POST"],
    types: {} as ChannelsIdJoinPost,
  },
  {
    params: ["uuid"],
    name: 'channels.leave',
    path: '/channels/:uuid/leave',
    method: ["DELETE"],
    types: {} as ChannelsIdLeaveDelete,
  },
  {
    params: ["channel_uuid"],
    name: 'channels.messages.store',
    path: '/channels/:channel_uuid/messages',
    method: ["POST"],
    types: {} as ChannelsIdMessagesPost,
  },
  {
    params: ["channel_uuid"],
    name: 'channels.messages.index',
    path: '/channels/:channel_uuid/messages',
    method: ["GET","HEAD"],
    types: {} as ChannelsIdMessagesGetHead,
  },
  {
    params: ["uuid"],
    name: 'channels.messages.destroy',
    path: '/channels/messages/:uuid',
    method: ["DELETE"],
    types: {} as ChannelsMessagesIdDelete,
  },
  {
    params: ["uuid"],
    name: 'channels.messages.react',
    path: '/channels/messages/:uuid/reactions',
    method: ["POST"],
    types: {} as ChannelsMessagesIdReactionsPost,
  },
  {
    params: [],
    name: 'surveys.show',
    path: '/surveys',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'surveys.results',
    path: '/surveys/results',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: ["uuid"],
    name: 'surveys.showResult',
    path: '/surveys/results/:uuid',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: ["uuid"],
    name: 'surveys.showSurvey',
    path: '/surveys/:uuid',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: ["uuid"],
    name: 'surveys.updateQuestion',
    path: '/surveys/:uuid/questions',
    method: ["PUT"],
    types: {} as unknown,
  },
  {
    params: ["uuid"],
    name: 'posts.report',
    path: '/posts/:uuid/report',
    method: ["POST"],
    types: {} as PostsIdReportPost,
  },
  {
    params: [],
    name: 'admin.reports.index',
    path: '/dashboard/admin/reports',
    method: ["GET","HEAD"],
    types: {} as DashboardAdminReportsGetHead,
  },
  {
    params: ["uuid"],
    name: 'admin.reports.reject',
    path: '/dashboard/admin/reports/:uuid/reject',
    method: ["PUT"],
    types: {} as DashboardAdminReportsIdRejectPut,
  },
  {
    params: ["uuid"],
    name: 'admin.reports.accept',
    path: '/dashboard/admin/reports/:uuid/accept',
    method: ["PUT"],
    types: {} as DashboardAdminReportsIdAcceptPut,
  },
  {
    params: [],
    name: 'admin.deleted-posts.index',
    path: '/dashboard/admin/deleted-posts',
    method: ["GET","HEAD"],
    types: {} as DashboardAdminDeletedpostsGetHead,
  },
  {
    params: ["uuid"],
    name: 'admin.deleted-posts.destroy',
    path: '/dashboard/admin/deleted-posts/:uuid',
    method: ["DELETE"],
    types: {} as DashboardAdminDeletedpostsIdDelete,
  },
  {
    params: [],
    name: 'settings.index',
    path: '/settings',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'profile.show',
    path: '/settings/profile',
    method: ["GET","HEAD"],
    types: {} as SettingsProfileGetHead,
  },
  {
    params: [],
    name: 'tokens.index',
    path: '/settings/tokens',
    method: ["GET","HEAD"],
    types: {} as SettingsTokensGetHead,
  },
  {
    params: ["id"],
    name: 'tokens.destroy',
    path: '/settings/tokens/:id',
    method: ["DELETE"],
    types: {} as SettingsTokensIdDelete,
  },
  {
    params: [],
    name: 'password.show',
    path: '/settings/password',
    method: ["GET","HEAD"],
    types: {} as SettingsPasswordGetHead,
  },
  {
    params: [],
    name: 'verification.wait',
    path: '/verification/wait',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: ["token"],
    name: 'verification.token',
    path: '/verification/:token',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'verification.resend',
    path: '/verification/resend',
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'configuration.campus.show',
    path: '/account/configure/campus',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'configuration.program.show',
    path: '/account/configure/program',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'account.preferences.update',
    path: '/account/preferences',
    method: ["PUT"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'users.ban',
    path: '/users/ban',
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: ["userUuid"],
    name: 'users.unban',
    path: '/users/unban/:userUuid',
    method: ["DELETE"],
    types: {} as unknown,
  },
  {
    params: ["uuid"],
    name: 'users.notifications.read',
    path: '/users/notifications/:uuid/read',
    method: ["POST"],
    types: {} as UsersNotificationsIdReadPost,
  },
  {
    params: ["uuid"],
    name: 'users.notifications.destroy',
    path: '/users/notifications/:uuid',
    method: ["DELETE"],
    types: {} as UsersNotificationsIdDelete,
  },
  {
    params: [],
    name: 'account.delete',
    path: '/users/me/delete',
    method: ["DELETE"],
    types: {} as unknown,
  },
  {
    params: ["uuid"],
    name: 'users.follow',
    path: '/users/follow/:uuid',
    method: ["POST"],
    types: {} as unknown,
  },
  {
    params: ["uuid"],
    name: 'users.unfollow',
    path: '/users/unfollow/:uuid',
    method: ["DELETE"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'ban.show',
    path: '/me/ban',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
declare module '@tuyau/inertia/types' {
  type InertiaApi = typeof api
  export interface Api extends InertiaApi {}
}
