/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    ForgotPassword: () => import('#app/auth/controllers/forgot_password_controller'),
    ResetPassword: () => import('#app/auth/controllers/reset_password_controller'),
    SignIn: () => import('#app/auth/controllers/sign_in_controller'),
    SignOut: () => import('#app/auth/controllers/sign_out_controller'),
    SignUp: () => import('#app/auth/controllers/sign_up_controller'),
    Social: () => import('#app/auth/controllers/social_controller'),
  },
  dashboard: {
    Admin: () => import('#app/dashboard/controllers/admin_controller'),
    Impersonates: () => import('#app/dashboard/controllers/impersonates_controller'),
    Invite: () => import('#app/dashboard/controllers/invite_controller'),
    RolesAdmin: () => import('#app/dashboard/controllers/roles_admin_controller'),
    Users: () => import('#app/dashboard/controllers/users_controller'),
  },
  users: {
    Account: () => import('#app/users/controllers/account_controller'),
    Bans: () => import('#app/users/controllers/bans_controller'),
    Password: () => import('#app/users/controllers/password_controller'),
    Profile: () => import('#app/users/controllers/profile_controller'),
    Tokens: () => import('#app/users/controllers/tokens_controller'),
    Verification: () => import('#app/users/controllers/verification_controller'),
  },
}
