/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BanSchema extends BaseModel {
  static $columns = ['bannedByUuid', 'createdAt', 'expiresAt', 'isActive', 'reason', 'updatedAt', 'userUuid', 'uuid'] as const
  $columns = BanSchema.$columns
  @column()
  declare bannedByUuid: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare isActive: boolean
  @column()
  declare reason: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userUuid: string
  @column({ isPrimary: true })
  declare uuid: string
}

export class ImpersonateTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'impersonatedUserUuid', 'originalUserUuid', 'tokenHash', 'updatedAt', 'uuid'] as const
  $columns = ImpersonateTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare impersonatedUserUuid: string
  @column()
  declare originalUserUuid: string
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column({ isPrimary: true })
  declare uuid: string
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class ResetPasswordTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'token', 'updatedAt', 'userUuid'] as const
  $columns = ResetPasswordTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userUuid: string | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'name', 'permissions', 'tag', 'tagColor', 'updatedAt', 'uuid'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare name: string
  @column()
  declare permissions: any
  @column()
  declare tag: string | null
  @column()
  declare tagColor: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
}

export class UserSchema extends BaseModel {
  static $columns = ['avatar', 'avatarUrl', 'banUuid', 'campus', 'createdAt', 'email', 'fullName', 'isBanned', 'isEmailVerified', 'password', 'preferences', 'program', 'roleUuid', 'track', 'updatedAt', 'uuid', 'year'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: any | null
  @column()
  declare avatarUrl: string | null
  @column()
  declare banUuid: string | null
  @column()
  declare campus: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column()
  declare isBanned: boolean
  @column()
  declare isEmailVerified: boolean
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare preferences: any | null
  @column()
  declare program: string | null
  @column()
  declare roleUuid: string | null
  @column()
  declare track: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
  @column()
  declare year: number | null
}

export class VerificationTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'token', 'updatedAt', 'userUuid'] as const
  $columns = VerificationTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userUuid: string
}

export class WebsiteSettingSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isMaintenance', 'maintenanceEndTime', 'maintenanceMessage', 'updatedAt'] as const
  $columns = WebsiteSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isMaintenance: boolean | null
  @column.dateTime()
  declare maintenanceEndTime: DateTime | null
  @column()
  declare maintenanceMessage: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
